# Generated by Django 5.1.3 on 2024-11-11 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição Breve')),
                ('categorias', models.ManyToManyField(to='despensa.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.despensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=127, unique=True)),
                ('prior', models.CharField(choices=[('S1', 'Baixa'), ('S2', 'Baixa Média'), ('S3', 'Média'), ('S4', 'Média Alta'), ('S5', 'Alta')], default='S3', max_length=2)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='despensa.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('preco', models.FloatField()),
                ('consumido', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('despensa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despensa.despensa')),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despensa.mercado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despensa.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField()),
                ('ListaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.listacompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despensa.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('S', 'Solicitado'), ('C', 'Confirmado'), ('N', 'Negado')], default='S', max_length=1)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='despensa.despensa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='despensa.despensa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensTransferidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.item')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.item')),
            ],
            options={
                'unique_together': {('item', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='QuantidadePadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_min', models.PositiveIntegerField(blank=True)),
                ('qtd_med', models.PositiveIntegerField(blank=True)),
                ('qtd_max', models.PositiveIntegerField(blank=True)),
                ('despensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.despensa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despensa.produto')),
            ],
            options={
                'unique_together': {('despensa', 'produto')},
            },
        ),
    ]
