# Generated by Django 5.1.3 on 2024-11-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='quantidadepadrao',
            options={'verbose_name_plural': 'Quantidades Padrão'},
        ),
        migrations.RenameField(
            model_name='produtoquantidade',
            old_name='ListaCompra',
            new_name='Lista_compra',
        ),
    ]
