# Generated by Django 5.1.3 on 2024-11-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0002_alter_item_options_alter_quantidadepadrao_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoquantidade',
            old_name='Lista_compra',
            new_name='lista_compra',
        ),
    ]
