# Generated by Django 5.1.3 on 2024-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0004_despensa_gerente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadepadrao',
            name='qtd_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantidadepadrao',
            name='qtd_med',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantidadepadrao',
            name='qtd_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
